### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by hrach** [stgeorgesepiscopal/google-meet-grid-view-extension#10]
Please, could you consider releasing a Firefox version?
Thanks :)

**Comment by antton** [comment]
Hi @hrach
I just released today in the morning!

https://addons.mozilla.org/es/firefox/addon/google-meet-grid-view/

Thanks for the original project!!

**Comment by hrach** [comment]
Thanks for the addon, closing here :)

**Comment by sreyemnayr** [comment]
@antton are you open-sourcing your firefox version? You'll need to make sure you stay up-to-date as Google will be releasing a native version of the functionality and we need to make sure users are eased into this.
