### ISSUE TITLE
Adjust grid when group chat bar is open

### ISSUE THREAD

**Issue by rb-109** [stgeorgesepiscopal/google-meet-grid-view-extension#4]
Add an option to shift the grid over when the group chat bar is open, so that it does not cover part of the grid.  That way, you can see all participants and the group chat at the same time.

**Comment by TheBox193** [comment]
This repo is only a Chrome Extension wrapper around [Fugiman/google-meet-grid-view](https://github.com/Fugiman/google-meet-grid-view). I recommend opening the suggestion there. 🙂

**Comment by rb-109** [comment]
Many thanks. I reached out to Fugiman and he has now implemented this change in his version 1.12.
(Issue #20)
Would you mind updating your version to incorporate his latest release? 

EDIT: Nevermind - I just saw that your latest version now incorporates this feature. Thank you again
