### ISSUE TITLE
International Donations Difficult

### ISSUE THREAD

**Issue by txoof** [stgeorgesepiscopal/google-meet-grid-view-extension#6]
Ryan,

I'm located in the Netherlands and wanted to drop a donation toward St. George in appreciation for the Grid plugin. The donations page is not configured properly to accept international credit/debit cards or paypal. Fortunately I have a US card that I can use, but a lot of your international traffic will likely not have access to a US card.

Thanks for the great plugin. 

If you have a guide for how to push this to all your users, I'd love to see that. I haven't dabbled in that yet, but I'd love to get it out to all our students.

**Comment by sreyemnayr** [comment]
Thanks! We should have a PayPal option on the school page now for international users :)

**Comment by sreyemnayr** [comment]
# Force Installing the Extension:
1. Go to admin.google.com > 3 bar "hamburger" menu at top left.
2. Devices > Chrome > Apps > Users & browsers
3. Select the OrgUnit to the left you want to force install. This would generally be the Students OrgUnit.
4. Click the yellow + circle at bottom right > click the "waffle" grid icon.
5. Choose "From the Chrome Web Store"
6. Search for Google Meet Grid View (ID: bjkegbgpfgpikgkfidhcihhiflbjgfic)
7. Click Save.
IMPORTANT: find the extension in the list and change it from "Allow install" to "Force install". Save changes.
